version: "3.8"
services:
  user-service:
    build: ./user-service
    ports:
      - "9081:8081"

  order-service:
    build: ./order-service
    ports:
      - "9082:8082"

  product-service:
    build: ./product-service
    ports:
      - "9083:8083"

  notification-service:
    build: ./notification-service
    ports:
      - "9084:8084"
